rvm:
  # - 1.9.2
  - 1.9.3
  - 2.0.0
  # - jruby-19mode
  # - jruby-18mode
  # - rbx-19mode
  # - rbx-18mode
  # - ruby-head

env:
  - "RAILS_VERSION=3.1.0"
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=master"

matrix:
  allow_failures:
    - rvm: ruby-head
    - env: "RAILS_VERSION=master"
  exclude:
    - rvm: 1.9.2
      env: "RAILS_VERSION=4.0.0"
    - rvm: 1.9.2
      env: "RAILS_VERSION=master"
  include:
    - rvm: 1.9.2
      env: "RAILS_VERSION=3.1.0"
    - rvm: 1.9.2
      env: "RAILS_VERSION=3.2.0"
    - rvm: ruby-head
      env: "RAILS_VERSION=4.0.0"